### ISSUE TITLE
EventEmitter2 reference incorrect

### ISSUE THREAD

**Issue by kmalakoff** [andrewjstone/measure#1]
it looks like this isn't right....

```
var EventEmitter = require('eventemitter2').EventEmitter2;
```

Should be:

```
var EventEmitter = require('eventemitter2');
```

**Comment by andrewjstone** [comment]
I haven't touched this code in 4 years, so it's possible that the EventEmitter2 interface has changed in the  intervening time. However, I just installed and ran the tests and they still pass, so this seems to work fine.

**Comment by andrewjstone** [comment]
Interface looks the same according to EventEmitter2 docs.

**Comment by kmalakoff** [comment]
Thanks for checking. I should have checked the source: https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L584

Strange it crashed the first time I ran it so I needed to make the change I'll investigate further...maybe it is a webpack thing.

**Comment by kmalakoff** [comment]
It was a known bug: https://github.com/asyncly/EventEmitter2/issues/146. 

I've submitted a pull request: https://github.com/asyncly/EventEmitter2/pull/156
